#!/usr/bin/env bash
# lib/gitconfig.sh — Git configuration generation (global + per-profile)
#
# Manages ~/.gitconfig (global) and ~/.config/gideon/profiles/<label>.gitconfig
# Uses managed block markers for idempotent updates.
# Bash 3.2 compatible.

# ------------------------------------------------------------------------------
# build_global_gitconfig_block — Generate the managed block for ~/.gitconfig
#
# Includes:
#   - Default [user] section (name, email)
#   - Default [core] sshCommand
#   - [init] defaultBranch = main
#   - [includeIf] entries for each non-default profile
#
# Usage: block=$(build_global_gitconfig_block)
# ------------------------------------------------------------------------------
build_global_gitconfig_block() {
    local gitdir_kw
    gitdir_kw=$(get_gitdir_keyword)

    local default_label="${PROFILE_LABELS[$DEFAULT_PROFILE_INDEX]}"
    local default_name="${PROFILE_NAMES[$DEFAULT_PROFILE_INDEX]}"
    local default_email="${PROFILE_EMAILS[$DEFAULT_PROFILE_INDEX]}"

    # Start with header and default user
    cat <<EOF
${GIDEON_MANAGED_START}
# Generated by gideon v${GIDEON_VERSION} on $(date +%Y-%m-%d)
# Do not edit between managed markers — gideon will overwrite on re-run.
# Everything outside these markers is preserved.

[user]
    name = ${default_name}
    email = ${default_email}

[core]
    sshCommand = ssh -i ~/.ssh/id_ed25519_${default_label}

[init]
    defaultBranch = main
EOF

    # Add safe.directory for each non-default profile (solves VirtualBox/WSL dubious ownership)
    local has_safe=0
    local i
    for i in $(seq 0 $((PROFILE_COUNT - 1))); do
        if [[ "$i" -eq "$DEFAULT_PROFILE_INDEX" ]]; then
            continue
        fi

        local dir="${PROFILE_DIRS[$i]}"
        if [[ -n "$dir" ]]; then
            if [[ "$dir" != */ ]]; then
                dir="${dir}/"
            fi
            
            if [[ "$has_safe" -eq 0 ]]; then
                printf '\n[safe]\n'
                has_safe=1
            fi
            printf '    directory = %s*\n' "$dir"
        fi
    done

    # Add includeIf for each non-default profile
    local i
    for i in $(seq 0 $((PROFILE_COUNT - 1))); do
        if [[ "$i" -eq "$DEFAULT_PROFILE_INDEX" ]]; then
            continue
        fi

        local label="${PROFILE_LABELS[$i]}"
        local dir="${PROFILE_DIRS[$i]}"

        if [[ -n "$dir" ]]; then
            # Ensure trailing slash for gitdir matching
            if [[ "$dir" != */ ]]; then
                dir="${dir}/"
            fi

            cat <<EOF

[includeIf "${gitdir_kw}${dir}"]
    path = ${GIDEON_PROFILES_DIR}/${label}.gitconfig
EOF
        fi
    done

    # Close managed block
    printf '%s\n' "${GIDEON_MANAGED_END}"
}

# ------------------------------------------------------------------------------
# write_global_gitconfig — Write/update ~/.gitconfig
#
# Strategy:
#   - If ~/.gitconfig exists with non-managed content: PRESERVE it,
#     only replace the managed block
#   - If ~/.gitconfig exists with managed block: replace managed block
#   - If no ~/.gitconfig: create fresh with only the managed block
#
# Usage: write_global_gitconfig
# ------------------------------------------------------------------------------
write_global_gitconfig() {
    local gitconfig="$HOME/.gitconfig"
    local managed_block
    managed_block=$(build_global_gitconfig_block)

    # Dry run
    if [[ "$GIDEON_DRY_RUN" -eq 1 ]]; then
        print_info "[DRY RUN] Would update: $gitconfig"
        print_info "[DRY RUN] Managed block contents:"
        local line
        while IFS= read -r line; do
            printf >&2 '    %s\n' "$line"
        done < <(printf '%s\n' "$managed_block")
        return 0
    fi

    # Backup existing
    if [[ -f "$gitconfig" ]]; then
        backup_file "$gitconfig"
    fi

    if [[ -f "$gitconfig" ]] && grep -q "\[gideon:managed:start\]" "$gitconfig" 2>/dev/null; then
        # File exists WITH managed block → replace it
        local tmp_file
        tmp_file=$(mktemp "${gitconfig}.tmp.XXXXXX")

        local in_managed=0
        local managed_written=0

        while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ "$line" == *"[gideon:managed:start]"* ]]; then
                in_managed=1
                # Write new managed block at this position
                if [[ "$managed_written" -eq 0 ]]; then
                    printf '%s\n' "$managed_block" >> "$tmp_file"
                    managed_written=1
                fi
                continue
            fi
            if [[ "$line" == *"[gideon:managed:end]"* ]]; then
                in_managed=0
                continue
            fi
            if [[ "$in_managed" -eq 0 ]]; then
                printf '%s\n' "$line" >> "$tmp_file"
            fi
        done < "$gitconfig"

        mv "$tmp_file" "$gitconfig"
        print_success "Updated managed block in: $gitconfig"

    elif [[ -f "$gitconfig" ]]; then
        # File exists WITHOUT managed block → append
        printf '\n%s\n' "$managed_block" >> "$gitconfig"
        print_success "Appended managed block to: $gitconfig"

    else
        # No file → create fresh
        printf '%s\n' "$managed_block" > "$gitconfig"
        print_success "Created: $gitconfig"
    fi
}

# ------------------------------------------------------------------------------
# build_profile_gitconfig — Generate a per-profile gitconfig
#
# Contains [user] and [core] sshCommand specific to this profile.
# This file is referenced by includeIf in the global gitconfig.
#
# Usage: content=$(build_profile_gitconfig "pro" "Bhaskar Jha" "bhaskar@email.com")
# ------------------------------------------------------------------------------
build_profile_gitconfig() {
    local label="$1"
    local name="$2"
    local email="$3"

    cat <<EOF
${GIDEON_MANAGED_START} Profile: ${label}
# Generated by gideon v${GIDEON_VERSION} on $(date +%Y-%m-%d)
# This config is auto-included when working in the '${label}' directory.

[user]
    name = ${name}
    email = ${email}

[core]
    sshCommand = ssh -i ~/.ssh/id_ed25519_${label}
${GIDEON_MANAGED_END} Profile: ${label}
EOF
}

# ------------------------------------------------------------------------------
# write_profile_gitconfig — Write a per-profile gitconfig file
#
# Creates: ~/.config/gideon/profiles/<label>.gitconfig
#
# Usage: write_profile_gitconfig "pro" "Bhaskar Jha" "bhaskar@email.com"
# ------------------------------------------------------------------------------
write_profile_gitconfig() {
    local label="$1"
    local name="$2"
    local email="$3"
    local profile_path="$GIDEON_PROFILES_DIR/${label}.gitconfig"

    local content
    content=$(build_profile_gitconfig "$label" "$name" "$email")

    if [[ "$GIDEON_DRY_RUN" -eq 1 ]]; then
        print_info "[DRY RUN] Would create: $profile_path"
        return 0
    fi

    ensure_dirs
    printf '%s\n' "$content" > "$profile_path"
    print_success "Created profile config: $profile_path"
}

# ------------------------------------------------------------------------------
# write_profiles_conf — Write the profile registry file
#
# Format: label:email:directory (one per line)
# Used by the guard hook to validate identities.
#
# Usage: write_profiles_conf
# ------------------------------------------------------------------------------
write_profiles_conf() {
    if [[ "$GIDEON_DRY_RUN" -eq 1 ]]; then
        print_info "[DRY RUN] Would create: $GIDEON_PROFILES_CONF"
        return 0
    fi

    ensure_dirs

    # Write header
    cat > "$GIDEON_PROFILES_CONF" <<EOF
# gideon profile registry — generated on $(date +%Y-%m-%d)
# Format: label:email:directory:provider
# Used by the pre-commit guard hook
EOF

    local i
    for i in $(seq 0 $((PROFILE_COUNT - 1))); do
        local label="${PROFILE_LABELS[$i]}"
        local email="${PROFILE_EMAILS[$i]}"
        local dir="${PROFILE_DIRS[$i]}"
        local provider="${PROFILE_PROVIDERS[$i]:-github.com}"
        
        printf '%s:%s:%s:%s\n' "$label" "$email" "$dir" "$provider" >> "$GIDEON_PROFILES_CONF"
    done

    print_success "Created profile registry: $GIDEON_PROFILES_CONF"
}
